### ISSUE TITLE
WWLK-k3e2n

### ISSUE THREAD

**Issue by LittlePea13** [Heidelberg-NLP/AMRParseEval#1]
Thank you for the nice work! I think AMR parsing evaluation will benefit from your work by giving insights on what works and what doesn't.

I would be interested in running the modified WWLK presented in the paper, WWLK-k3e2n, but I am unsure if it is currently possible with the current state of the repo. If possible, could you indicate how?

Thanks again,
Pere-Lluis.

**Comment by flipz357** [comment]
Hi Pere-Lluis! I think it runs with the command:

```
python -u main_wlk_wasser.py -a <amr_predicted> -b <amr_ref> \
                              -output_type score_corpus \
                              -stability_level 15 -k 3 \
                              -random_init_relation ones \
                              --edge_to_node_transform
```

See also in the [weisfeiler-Leman repo](https://github.com/flipz357/weisfeiler-leman-amr-metrics) or in `evaluation-suite/run_wwl.sh` of this repo. You may have to install some python modules (scipy, gensim etc), see Readme of the metric.

Best,

Juri

**Comment by LittlePea13** [comment]
thanks!
